# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_crud_city'),
    ]

    operations = [
    ]
