# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20190101_1421'),
    ]

    operations = [
    ]
