# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20190101_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='city',
        ),
    ]
