# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_auto_20190101_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Crud',
        ),
    ]
