# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_city_crud'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
